name: Test Unit Tests
on:
  pull_request:

permissions:
  contents: read

# Abort prior jobs in the same workflow / PR
concurrency:
  group: unit-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate-unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: setup go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Run unit tests
        run: make test
